# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'razeUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_razeUi(object):
    def setupUi(self, razeUi):
        razeUi.setObjectName("razeUi")
        razeUi.resize(1833, 1020)
        self.centralwidget = QtWidgets.QWidget(razeUi)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1831, 1021))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../sage/download.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1580, 950, 93, 28))
        self.pushButton.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1680, 950, 93, 28))
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 675, 401, 341))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(
            "../sage/tumblr_ce7d7e9e05ff652350d42c36183dc035_11702cad_500.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(1520, 30, 256, 51))
        self.textBrowser.setStyleSheet("background:transparent;\n"
                                       "border-radius:none;\n"
                                       "color:white;\n"
                                       "font-size:20px;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(1250, 30, 256, 51))
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
                                         "border-radius:none;n"
                                         "color:white;\n"
                                         "font-size:20px;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        razeUi.setCentralWidget(self.centralwidget)

        self.retranslateUi(razeUi)
        QtCore.QMetaObject.connectSlotsByName(razeUi)

    def retranslateUi(self, razeUi):
        _translate = QtCore.QCoreApplication.translate
        razeUi.setWindowTitle(_translate("razeUi", "MainWindow"))
        self.pushButton.setText(_translate("razeUi", "Run"))
        self.pushButton_2.setText(_translate("razeUi", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    razeUi = QtWidgets.QMainWindow()
    ui = Ui_razeUi()
    ui.setupUi(razeUi)
    razeUi.show()
    sys.exit(app.exec_())
